using System;

namespace dotWork.Tests.TestExceptions
{
    class IterationFinishedException : Exception
    {
    }
}
